# https://bun.sh/docs/runtime/bunfig

# package manager configuration here
[install]
optional = true
dev = true
peer = true
production = false # Ignore dev dependencies. Use --production in the CLI to override.
globalDir = "/Users/alex/.cache/.bun/install/global"
globalBinDir = "/Users/alex/.cache/.bun/bin"

[install.cache]
dir = "/Users/alex/.cache/.bun/install/cache"
